// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGICb0pohY3933JSDvH5CmllXhmoWUDj4',
    appId: '1:384813033549:web:0d7f017da7489d36be1404',
    messagingSenderId: '384813033549',
    projectId: 'login-flutter-9b49f',
    authDomain: 'login-flutter-9b49f.firebaseapp.com',
    storageBucket: 'login-flutter-9b49f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyIhZHOeYnVQZxMhgVcbdIEAi_Ylo-l80',
    appId: '1:384813033549:android:a818cde0baac5676be1404',
    messagingSenderId: '384813033549',
    projectId: 'login-flutter-9b49f',
    storageBucket: 'login-flutter-9b49f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACcXEpltFMihLITeMW0zKyotzQ3qqGuys',
    appId: '1:384813033549:ios:67f182ff4720e2f5be1404',
    messagingSenderId: '384813033549',
    projectId: 'login-flutter-9b49f',
    storageBucket: 'login-flutter-9b49f.appspot.com',
    iosBundleId: 'com.example.loginScreen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGICb0pohY3933JSDvH5CmllXhmoWUDj4',
    appId: '1:384813033549:web:d978f9756723b1bfbe1404',
    messagingSenderId: '384813033549',
    projectId: 'login-flutter-9b49f',
    authDomain: 'login-flutter-9b49f.firebaseapp.com',
    storageBucket: 'login-flutter-9b49f.appspot.com',
  );
}
